#debug: true


## configuration of server info
server:
  port: 9999



## properties configuration
app:
  name: SpringBootStarterDemo
  description: ${app.name} is a Spring boot Application
  first_name: underlineName
  first-name: stripingLineName

prefix:
  multiLines1:
    - a
    - b
  multiLines2: a,b
  poolSize: 10
  executorPool:
    corePoolSize: 10
    maxPoolSize: 100
    queueSize: 500


## log confi
logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: debug
  file: /Users/zhouyangzhou/work/temp/springbootstarter/spring.log

